name: CI Test (Behave) Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  behave-tests:
    runs-on: ubuntu-latest # use linux os

    permissions:
      contents: read
      issues: write
      checks: write
      pull-requests: write
    
    steps:
      #Step 1: checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3 #v3
      - name: print content of repo
        run:  |
          ls
      
      #Step 2: setup python environment
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' #specify the python version
      
      #Step 3: install dependencies
      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install behave
      
      #Step 4: run tests from the features folder
      - name: Run tests
        run:  |
          mkdir -p test-results
          behave features/ --junit --junit-directory=test-results
          ls  test-results/
      
      #Step 5a: Upload Test results

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          path: test-results

      #Step: 5b: Publish Test results
      - name: Publish test Results
        uses:  actions/github-script@v6
        with:  
          script: |
            const checkRun = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "Behave Tests",
              head_sha: context.sha,
              status: "completed",
              conclusion: "${{job.status}}",  //  'success' or 'failure'
              output: {
                title:  "Behave Tests Results",
                summary:  "See the test logs  for more details.",
                text: "The behave tests ran successfully or failed depending on the outcome."
              }
            });
            console.log(checkRun);
      

      #Step 6a: Create Issue
      - name: Create an issue if tests fail
        if: failure() #run this only if the previous steps fail
        uses: peter-evans/create-issue-from-file@v3
        with: 
          title:  "Test failure detected"
          body: "Test have failed in the behave tests. please review the logs."
          labels: "bug"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: junit-test-results
        
      - name: Send Telegram Message on Test Failure(s)
        if: failure()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
          -d chat_id="${TELEGRAM_CHAT_ID}" \
          -d text="Review failed run, fix the issue(s), and re-run until successful." 
      # Step 7: CD (Prepare files for delivery/deployment)-individual name
      - name: Prepare files
        run: |
          mkdir -p release
          cp -r ./calculators.py ./release/calculator-Ng_Thian_Ping.py
          echo "Deployment files prepared."
          ls -l ./release/

      # Step 8: Upload files to AWS S3
      - name: Upload to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
        run: |
          aws s3 cp ./release s3://devops-calculator-app/release-files --recursive
      
